name: Bug report
description: Report a bug in one of the modules
labels: [bug]
body:
  - type: input
    id: module
    attributes:
      label: Affected module
      placeholder: e.g., crudapp, SpringSecurityJWT
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/errors
